services:
  db:
    image: postgres
    env_file: ".env"
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - ./cache:/data
  backend:
    build: ./backend
    env_file: ".env"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    restart: always
  caddy-serv:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs/localhost.crt:/etc/caddy/localhost.crt
      - ./certs/localhost.key:/etc/caddy/localhost.key
      - ./frontend/:/usr/share/caddy
    ports:
      - "443:443"
      - "8000:8000"
    depends_on:
      - backend