services:
  db:
    image: postgres
    env_file: ".env"
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file: ".env"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    restart: always
  caddy-serv:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/:/usr/share/caddy
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - backend